### ISSUE TITLE
pixel2world

### ISSUE THREAD

**Issue by NJUPTWyx** [Leeiieeo/3D-photography-on-your-desk#1]
请问，在world2pixel中，camera[2]应该是尺度因子把，但是为什么在pixel2world的计算中没有体现这个

**Comment by Leeiieeo** [comment]
您好，world2pixel是讲世界坐标系下的点映射到像素坐标系下的过程，输入是世界坐标[x, y, z]，输出是像素坐标[px, py]，是在已知该点的深度下进行的，其实是信息压缩的过程，因为一旦映射到2维的像素坐标系之后就损失了深度信息，恢复不回去了。
因此，在pixel2camera和pixel2world中是无法恢复深度信息的，所以尺寸因子或者是相机坐标系下的z坐标是被固定成1的，即先将像素坐标变换到所谓的归一化平面（就是相机坐标系下z=1的平面），然后再变换到世界坐标系下。这两个过程分别对应pixel2camera和camera2world。可能我在pixel2camera里面注释一下“将像素点映射到相机坐标系归一化平面”更不容易产生误解。
